name: PrintGuard CI

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Project Dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Pylint
        run: |
          pip install pylint

      - name: Compile Sensor Simulator
        run: |
          python -m compileall sensor_simulator

      - name: Compile Fog Node
        run: |
          python -m compileall fog_node

      - name: Run Pylint (Sensor Simulator)
        run: |
          pylint sensor_simulator --fail-under=7 || true

      - name: Run Pylint (Fog Node)
        run: |
          pylint fog_node --fail-under=7 || true

      - name: Display Project Structure
        run: |
          ls -R